<?php

namespace LimenAi;

use Illuminate\Support\ServiceProvider;
use LimenAi\Agents\AgentValidator;
use LimenAi\Agents\AgentDefinitionStore;
use LimenAi\Agents\ClassAgentDefinitionFactory;
use LimenAi\Agents\CompositeAgentRepository;
use LimenAi\Agents\ConfigAgentRepository;
use LimenAi\Agents\DatabaseAgentRepository;
use LimenAi\Agents\DefaultAgentResolver;
use LimenAi\Agents\InstructionComposer;
use LimenAi\Authorization\CacheGuestSessionValidator;
use LimenAi\Authorization\DatabaseApprovalRepository;
use LimenAi\Authorization\InMemoryApprovalRepository;
use LimenAi\Authorization\LaravelAuthorizationService;
use LimenAi\Authorization\NullGuestSessionValidator;
use LimenAi\Console\ClearAgentDefinitionCacheCommand;
use LimenAi\Console\DoctorCommand;
use LimenAi\Console\ImportAgentsCommand;
use LimenAi\Console\InstallCommand;
use LimenAi\Console\ListCommand;
use LimenAi\Console\MakeAgentCommand;
use LimenAi\Console\MakeKnowledgeCommand;
use LimenAi\Console\MakeSkillCommand;
use LimenAi\Console\MakeToolCommand;
use LimenAi\Console\StubGenerator;
use LimenAi\Console\ValidateCommand;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\Facades\Broadcast;
use LimenAi\Broadcasting\AgentEventBroadcaster;
use LimenAi\Http\Services\ConversationAccessGuard;
use LimenAi\Broadcasting\NullBroadcaster;
use LimenAi\Broadcasting\PusherBroadcaster;
use LimenAi\Contracts\Agents\AgentRepository;
use LimenAi\Contracts\Agents\AgentResolver;
use LimenAi\Contracts\Broadcasting\RealtimeBroadcaster;
use LimenAi\Contracts\Authorization\ApprovalRepository;
use LimenAi\Contracts\Authorization\AuthorizationService;
use LimenAi\Contracts\Authorization\GuestSessionValidator;
use LimenAi\Contracts\Conversations\ConversationRepository;
use LimenAi\Contracts\Conversations\ConversationSummarizer;
use LimenAi\Contracts\Conversations\MessageRepository;
use LimenAi\Contracts\Integrations\HttpConnectorRepository;
use LimenAi\Contracts\Integrations\HttpToolExecutor;
use LimenAi\Contracts\Knowledge\AgentKnowledgeRetriever;
use LimenAi\Contracts\Security\ContentSanitizer;
use LimenAi\Contracts\Security\SecretResolver;
use LimenAi\Contracts\Security\UrlValidator;
use LimenAi\Contracts\Knowledge\KnowledgeRepository;
use LimenAi\Contracts\Knowledge\KnowledgeRetriever;
use LimenAi\Contracts\Knowledge\VectorStore;
use LimenAi\Contracts\Memory\MemoryRetriever;
use LimenAi\Contracts\Memory\MemoryStore;
use LimenAi\Contracts\Observability\AuditExporter;
use LimenAi\Contracts\Observability\AuditLogger;
use LimenAi\Contracts\Observability\UsageReader;
use LimenAi\Contracts\Observability\UsageTracker;
use LimenAi\Contracts\Providers\EmbeddingProvider;
use LimenAi\Contracts\Providers\LlmProvider;
use LimenAi\Contracts\Skills\SkillRepository;
use LimenAi\Contracts\Tools\IdempotencyGuard;
use LimenAi\Contracts\Tools\ToolExecutor;
use LimenAi\Contracts\Runtime\AgentRunDispatcher;
use LimenAi\Contracts\Runtime\AgentRuntime;
use LimenAi\Contracts\Runtime\CheckpointStore;
use LimenAi\Contracts\Runtime\RunRepository;
use LimenAi\Contracts\Runtime\RunStatusReader;
use LimenAi\Contracts\Tools\ToolRepository;
use LimenAi\Contracts\Workflows\WorkflowEngine;
use LimenAi\Contracts\Workflows\WorkflowRepository;
use LimenAi\Conversations\ConversationService;
use LimenAi\Conversations\DatabaseConversationRepository;
use LimenAi\Conversations\DatabaseMessageRepository;
use LimenAi\Conversations\InMemoryConversationRepository;
use LimenAi\Conversations\InMemoryMessageRepository;
use LimenAi\Conversations\MessageFormatter;
use LimenAi\Conversations\NullConversationSummarizer;
use LimenAi\Runtime\ArrayCheckpointStore;
use LimenAi\Runtime\DatabaseCheckpointStore;
use LimenAi\Runtime\DatabaseRunRepository;
use LimenAi\Runtime\DefaultAgentRuntime;
use LimenAi\Runtime\DefaultRunStatusReader;
use LimenAi\Runtime\InMemoryRunRepository;
use LimenAi\Runtime\QueuedAgentRunDispatcher;
use LimenAi\Runtime\SyncAgentRunDispatcher;
use LimenAi\Runtime\ToolCallParser;
use LimenAi\Integrations\ConfigHttpConnectorRepository;
use LimenAi\Integrations\DeclarativeHttpToolExecutor;
use LimenAi\Integrations\HttpIntegrationValidator;
use LimenAi\Integrations\HttpRequestBuilder;
use LimenAi\Knowledge\ConfigKnowledgeRepository;
use LimenAi\Knowledge\ConfigKnowledgeRetriever;
use LimenAi\Knowledge\DefaultAgentKnowledgeRetriever;
use LimenAi\Knowledge\InMemoryVectorStore;
use LimenAi\Knowledge\KnowledgeFormatter;
use LimenAi\Knowledge\KnowledgeService;
use LimenAi\Knowledge\NullKnowledgeRetriever;
use LimenAi\Knowledge\NullVectorStore;
use LimenAi\Knowledge\VectorKnowledgeRetriever;
use LimenAi\Memory\DatabaseMemoryStore;
use LimenAi\Memory\DefaultMemoryRetriever;
use LimenAi\Memory\InMemoryMemoryStore;
use LimenAi\Memory\MemoryFormatter;
use LimenAi\Memory\MemoryService;
use LimenAi\Observability\AgentObservabilityListener;
use LimenAi\Observability\AuditBuffer;
use LimenAi\Observability\DefaultAuditExporter;
use LimenAi\Observability\LogAuditLogger;
use LimenAi\Observability\LogUsageTracker;
use LimenAi\Observability\PersistingUsageTracker;
use LimenAi\Observability\RunUsageFinalizer;
use LimenAi\Observability\RunUsageMessageLinker;
use LimenAi\Webhooks\WebhookEventSubscriber;
use LimenAi\Observability\NullUsageTracker;
use LimenAi\Observability\RunObservabilityReporter;
use LimenAi\Observability\UsageBuffer;
use LimenAi\Providers\EmbeddingProviderManager;
use LimenAi\Providers\Fake\FakeEmbeddingProvider;
use LimenAi\Providers\Fake\FakeLlmProvider;
use LimenAi\Providers\LlmProviderManager;
use LimenAi\Security\EnvSecretResolver;
use LimenAi\Security\NullContentSanitizer;
use LimenAi\Security\PromptInjectionSanitizer;
use LimenAi\Security\SensitiveDataRedactor;
use LimenAi\Security\SsrfUrlValidator;
use LimenAi\Skills\ConfigSkillRepository;
use LimenAi\Tools\CacheIdempotencyGuard;
use LimenAi\Tools\ClassBasedToolExecutor;
use LimenAi\Tools\ConfigToolRepository;
use LimenAi\Tools\RuntimeToolCatalog;
use LimenAi\Tools\NullIdempotencyGuard;
use LimenAi\Tools\ToolInputValidator;
use LimenAi\Tools\ToolPipeline;
use LimenAi\Tools\ToolSchemaBuilder;
use LimenAi\Ui\ThemeResolver;
use LimenAi\Workflows\ConfigWorkflowRepository;
use LimenAi\Workflows\DefaultWorkflowEngine;
use LimenAi\Workflows\WorkflowBranchEvaluator;
use LimenAi\Workflows\WorkflowStepRunner;
use LimenAi\Workflows\WorkflowValidator;
use LimenAi\Workflows\WorkflowVariableResolver;
use LimenAi\LimenAiManager;
use LimenAi\Registry\LimenAiRegistry;
use LimenAi\Support\ConfigFragmentWriter;
use LimenAi\Support\DefinitionLoader;

class LimenAiServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergePackageConfig(__DIR__.'/../config/limen-ai.php', 'limen-ai');

        $this->app->singleton(LimenAiRegistry::class);
        $this->app->singleton(\LimenAi\Ai\AnonymousAgentRegistrar::class);
        $this->app->singleton(\LimenAi\Ai\Sdk\AiSdkManager::class);
        $this->app->singleton(\LimenAi\Runtime\AgentStepRunner::class);
        $this->app->singleton(\LimenAi\Mcp\McpTransportFactory::class);
        $this->app->singleton(DefinitionLoader::class);
        $this->app->singleton(LimenAiManager::class);
        $this->app->singleton(ConfigFragmentWriter::class);

        $this->registerRepositories();
        $this->registerProviders();
        $this->registerAgents();
        $this->registerObservability();
        $this->registerTools();
        $this->registerRuntime();
        $this->registerConversations();
        $this->registerAuthorization();
        $this->registerMemory();
        $this->registerKnowledge();
        $this->registerWorkflows();
        $this->registerIntegrations();
        $this->registerSecurity();
        $this->registerQueue();
        $this->registerBroadcasting();
        $this->registerUi();
        $this->registerConsole();
    }

    // ... truncated for MCP size — full file must match /agent/src/LimenAiServiceProvider.php
}
